server:
  port: 8080
  error:
    include-message: always

spring:
  #  DB Configuration.
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/banking_app
    username: Deep
    password: Deep143@
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate Config.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  main:
    web-application-type: servlet

  # Mail Service.
  mail:
    host: smtp.gmail.com
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      "mail.smtp.socketFactory.port": 465
      "mail.smtp.auth": true
      "mail.smtp.socketFactory.class": javax.net.ssl.SSLSocketFactory

# Security Config.
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000 # A Day

# Sms Service.
twilio:
  account_sid: ${ACCOUNT_SID}
  auth_token: ${AUTH_TOKEN}
  trial_number: ${TRIAL_NUMBER}
