server:
  port: 8080
  error:
    include-message: always

spring:
  #  DB Configuration.
  datasource:
    url: jdbc:mysql://db:3306/banking_app
    username: root
    password: password
    initialization-mode: always

  # Hibernate Config.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  main:
    web-application-type: servlet

  # Mail Service.
  mail:
    host: smtp.gmail.com
    username:
    password:
    properties:
      "mail.smtp.socketFactory.port": 465
      "mail.smtp.auth": true
      "mail.smtp.socketFactory.class": javax.net.ssl.SSLSocketFactory

# Security Config.
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # A Day

# Sms Service.
twilio:
  accountSid:
  authToken:
  trialNumber: